spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Admin@123
    virtual-host: etugoal

server:
  port: 8080

swagger:
  enable: true

mail:
  user: madking
  password: aaa123

---
spring:
  profiles: test
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: Admin@123
    virtual-host: etugoal

server:
  port: 9527

swagger:
  enable: true

mail:
  user: madking
  password: aaa123